openapi: 3.0.1
info:
  title: node-docker-app
  description: Playground for docker and node
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: Users
    description: Simple user endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /users:
    post:
      tags:
        - Users
      description: Create a new user
      requestBody:
        description: this is simple user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        201:
          description: Returns the newly created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExistingUser'
        4XX:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /users/{email}:
    get:
      tags:
        - Users
      parameters:
        - name: email
          in: path
          description: The email of the user to retrieve
          required: true
          schema:
            type: string
      responses:
        200:
          description: Returns the user with the specified email
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExistingUser'
        4XX:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      tags:
        - Users
      description: this is updating user info
      parameters:
        - name: email
          in: path
          description: The email of the user to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: User details to be updated
        content:
          application/json:
            schema:
              $ref: '#components/schemas/UpdateUser'
      responses:
        200:
          description: Returns the updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExistingUser'
        4XX:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      tags:
        - Users
      description: Delete existing user by email
      parameters:
        - name: email
          in: path
          description: The email of the user to be deleted
          required: true
          schema:
            type: string
      responses:
        200:
          description: Returns OK
        4XX:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    ExistingUser:
      type: object
      properties:
        id:
          type: string
          example: g31sdGs8
        email:
          type: string
          example: iliyan@best-email.com
        givenName:
          type: string
          example: Iliyan
        familyName:
          type: string
          example: Vlahov
        created:
          type: string
          format: date-time
          example: 2021-10-21T14:32:28Z
    CreateUser:
      required:
        - email
        - givenName
        - familyName
      type: object
      properties:
        email:
          type: string
          example: iliyan@my-email.com
        givenName:
          type: string
          minLength: 2
          maxLength: 30
          example: Iliyan
        familyName:
          type: string
          minLength: 2
          maxLength: 30
          example: Vlahov
    UpdateUser:
      type: object
      minProperties: 1
      maxProperties: 3
      properties:
        givenName:
          type: string
          minLength: 2
          maxLength: 30
          example: RenameMyFirstName
        familyName:
          type: string
          minLength: 2
          maxLength: 30
          example: RenameMyLastName
    Error:
      type: object
      properties:
        message:
          type: string
          example: Not found
        status:
          type: integer
          example: 404
      additionalProperties: true
    InternalServerError:
      type: object
      properties:
        message:
          type: string
          example: Something went wrong, please try again later.
        status:
          type: integer
          example: 500
        statusCode:
          type: integer
          example: 500
      additionalProperties: true
